/* @flow */

export const INVALIDATE_WEATHER = 'INVALIDATE_WEATHER'
export const FETCH_WEATHER = 'FETCH_WEATHER'
export const FETCH_WEATHER_FULFILLED = 'FETCH_WEATHER_FULFILLED'
export const FETCH_WEATHER_REJECTED = 'FETCH_WEATHER_REJECTED'
